# Generated by Django 4.0.2 on 2022-02-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('SC', 'SELF CONTAINED'), ('SR', 'SINGLE ROOM'), ('DB', 'DORMITORY BUNKS'), ('DB', 'DORMITORY BUNKS'), ('DB', 'DORMITORY BUNKS')], max_length=2)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
