# Generated by Django 4.0.2 on 2022-02-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='number',
            new_name='rooms',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(choices=[('SC', 'SELF CONTAINED'), ('SR', 'SINGLE ROOM'), ('DB', 'DORMITORY BUNKS')], max_length=2),
        ),
    ]
