# Generated by Django 4.0.2 on 2022-02-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_rename_number_rooms_rooms_alter_rooms_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='capacity',
        ),
    ]
