# Generated by Django 4.0.2 on 2022-02-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
